let mgQuotes1 = [`I'm sorry that people are so jealous of me. But I can't help it that I'm popular. Whoever wrote it probably didn't think anyone would ever see it? I hope that nobody else ever does see it. Whatever. I'm getting cheese fries. Regina George. Coach Carr, step away from the underage girls! On Wednesdays we wear pink! I'm not like a regular mom. I'm a cool mom. Irregardless! Ex-boyfriends are just off limits to friends. I mean, that's just like, the rules of feminism!`]

let mgQuotes2 = [`Four for you Glen Coco, You GO Glen Coco! ....And none for Gretchen Weiners.Bye. I hate her! I mean, she's really failing me on purpose, just because I didn't join that stupid Mathletes! She was so queer, she was like, I'm pusher Cady, I'm a pusher. Cady Heron. Why are dressed so scary? It's Halloween. I can't go out. I'm sick. Boo! You whore! She doesn't even go here! I don’t think that my father, the inventor of Toaster Strudel, would be too pleased to hear about this`]

let mgQuotes3 = [`Watch out please! Fresh meat coming through! I hated Regina George! I hated her!Oh, hi. Did you wanna buy some drugs? Every one grab some rubbers. That is so fetch! Gretchen Weiners. Don't have sex. Because you will get pregnant, and die. Don't have sex in the missionary position, don't have sex standing up, just... don't do it. Promise?`]

let mgQuotes3 = [`So you're, like, really pretty. Thank you. So you agree? What? You think you're really pretty? You wanna do something fun? You wanna go to Taco Bell? I can't go to Taco Bell! I'm on an all-carb diet! God, Karen, you are so stupid! This is Susan from Planned Parenthood. I have her test results. If you could have her call me as soon as she can? It's urgent. Thank you! Gretchen, stop trying to make *fetch* happen. It's not going to happen! Boo, you whore.`]

let mgQuotes4 [`Somebody wrote in the book that I'm lying about being a virgin because I use XXL tampons, but It's not my fault I have a heavy flow and a wide-set vagina! Karen Smith.  Wow Damian you've truly outgayed yourself. There's a 30% chance that it's already raining... In the real world, Halloween is when kids dress up and beg for candy. But in girl world, Halloween is the one time of year a girl can dress like a total slut and no other girl can say anything about it. No one had told me about the girl world rule.`]

let mgQuotes5 = [`Somebody should just stab Ceasar. On Wednesdays we wear pink! Gretchen, I'm sorry I laughed at you that time you got diarrhea at Barnes & Noble. And I'm sorry for telling everyone about it. And I'm sorry for repeating it now. Oh my God, Karen! You can't just ask people why they're white! No, I know what home-school is, I'm not retarded! So you've actually never been to a real school before? Shut up! Shut up! Gretchen, stop trying to make fetch happen! It's not going to happen! You smell like a baby prostitute. Hey, buddy, you're not pretending anymore. You're plastic. Cold, shiny, hard plastic!`]

let mgQuotes6 = [`See? That's the thing with you plastics. You think everybody is in love with you when actually, everybody HATES you! Like, Aaron Samuels, for example, he broke up with Regina and guess what? He still doesn't want you! So why are you still messing with Regina, Cady? I'll tell you why, because you are a mean girl! You're a bitch! Here. You can have this. It won a prize! Hell, no. I did *not* leave the South Side for this!  And that's how Regina died, no I'm totally kidding but she was hurt. Some people say the bus meant to hit her, but that was just a rumor. Other people said that 'I' pushed her. That was a even worse rumor.`]

let mgQuotes7 = [`Where's Cady? Oh she went out. But she's grounded. Oh are they not allowed out when they're grounded? I'm not a regular mom, I'm a cool mom! Beware of plastics. And none for Gretchen Weiners. Bye.Don't have sex. Because you will get pregnant. And die. Get in loser, we're going shopping. I'm a mouse. Duh! Boo, you whore. Those bitches! I'm sorry that people are so jealous of me. But I can't help it that I'm popular. That's why her hair is so big. It's full of secrets! Make sure you check out her mom's boob job. They're hard as rocks! `]

let mgQuotes8 = [`I don't know why. Its probably because I have a big, fat LESBIAN crush on you. Suck on that! Aye aye aye! Your mom's chest hair! You can't sit with us! So if you're from Africa....then why are you white? Glenn Coco? FOUR for you, Glenn Coco! You go, Glenn Coco! Is butter a carb? One time I saw Cady Heron wearing army pants and flip flops. So I bought army pants and flip flops. Get in, loser. We're going shopping!I can't go to Taco Bell, I'm on an all-carb diet! God, Karen! You're so stupid!`]

let mgQuotes9 = [`Made out with a hot dog'? Oh my god! That was one time!And while we have you here, we guess it's as good a time as any to tell you that we're sorry we called you a gap-toothed bitch. It's not your fault you're so gap-toothed. That is so fetch! That’s why her hair is so big. It’s full of secrets. It’s like I have ESPN or something. My breasts can always tell when it’s going to rain. Well…they can tell when it’s raining. Can I get you guys anything? Some snacks? A condom? Let me know! Oh, God love ya. I don’t think that my father, the inventor of Toaster Strudel, would be too pleased to hear about this`]
